### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by DanRoman-code**

### CODE REVIEW

**Review by DmytroSvirsa — CHANGES_REQUESTED** [review]
Good job, but remove .idea files

**Review by DmytroSvirsa — CHANGES_REQUESTED** [review]
and remove db.sqlite3

**Comment by DanRoman-code** [comment]
> and remove db.sqlite3

It doest clicable for delete (

**Review by DmytroSvirsa — CHANGES_REQUESTED** [review]
now remove `__pycache__`

**Pull request closed without merging**
